In [4]:
#Import numpy as np and see the version
import numpy as np
print(np.__version__)

1.14.0


In [4]:
#Create a 1D array of numbers from 0 to 9
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#Create a 3X3 numpy array of all True's
np.full((3,3), True,dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [10]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [14]:
#Extract all odd numbers from arr
arr = np.array([0,1,2,3,4,5,6,7,8,9,10])
arr2 = arr[arr % 2 == 1]
arr2

array([1, 3, 5, 7, 9])

In [15]:
#Replace all odd numbers in array with -1
arr[arr%2==1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [16]:
#Replace all odd numbers in arr with -1 without changing out
out = np.where(arr%2==1,-1,arr)
print(arr)
out

[ 0 -1  2 -1  4 -1  6 -1  8 -1 10]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [23]:
#Convert a One Dimsional array with two dimensional array with 2 rows
arr = np.arange(10)
arr.reshape(2,-2)#Setting -1 automatically decodes the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
#Stack two array vertically
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
#Method 1
np.concatenate([a,b],axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [34]:
#Method 2
np.r_[a,b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [35]:
#Method 3
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [38]:
#Stack two arrays vertically
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
#Method 1
np.concatenate([a,b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [39]:
#Method 2
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [40]:
#Method 3
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [44]:
#Generate custom sequence in numpy
a = np.array([1,2,3])
#Method 1 Horizontal
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [45]:
#Method 2 Vertical
np.c_[np.repeat(a,3),np.tile(a,3)]

array([[1, 1],
       [1, 2],
       [1, 3],
       [2, 1],
       [2, 2],
       [2, 3],
       [3, 1],
       [3, 2],
       [3, 3]])

In [53]:
#Get commonitems between two numpy arrays
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([2,7,7,7,4,7,8,9,7])
np.intersect1d(a,b)

array([2, 4, 7, 8, 9])

In [54]:
#Remove from one array those items exists in another
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [59]:
#Get positions where elements of array a and b match
a = np.array([1,2,3,4,5,6,7,3,3,6,6])
b = np.array([1,4,5,3,5,7,4,6,3,5,7])
np.where(a == b)

(array([0, 4, 8], dtype=int32),)

In [64]:
#Extract all numers between a given range
#Get all items between 5 and 10 from array a
a = np.arange(15)
#Method 1
index = np.where((a>5) & (a<10))
a[index]

array([6, 7, 8, 9])

In [66]:
#Method 2
index = np.where(np.logical_and(a>5, a<10))
a[index]

array([6, 7, 8, 9])

In [74]:
#Method 3
a[(a > 5) & (a < 10)]

array([6, 7, 8, 9])

In [79]:
#Use python function that handles scalar values and work on arrays
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max = np.vectorize(maxx, otypes=[int])
pair_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])

In [80]:
#Swap two columns in a 2d numpy array
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [81]:
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [84]:
#Swap two rows in a 2d array
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [86]:
#Reverse the Rows of a 2D array
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [87]:
#Reverse Columns of a 2D array
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [96]:
#Create a 2D array contain random float between 5 and 10
#Method 1
np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))

array([[8.87969817, 5.47297135, 8.05996508],
       [5.24579804, 9.57338412, 6.96202785],
       [9.70964393, 5.38305418, 6.87943679],
       [8.29789429, 9.17201105, 5.16843866],
       [8.54714146, 8.79491283, 9.11976685]])

In [100]:
#Method 2
np.random.uniform(5,10,size=(5,3))

array([[5.67850401, 5.61248443, 8.56743482],
       [6.36033275, 9.89431374, 8.06425103],
       [5.24342467, 8.99133432, 9.94499551],
       [6.38357109, 6.81413564, 9.27982044],
       [6.51706309, 7.8433851 , 9.49294885]])

In [111]:
#Print only 2 decimal places in array
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=2)
rand_arr

array([[0.42, 0.62, 0.47],
       [0.16, 0.3 , 0.24],
       [0.81, 0.19, 0.69],
       [0.86, 0.52, 0.24],
       [0.45, 0.12, 0.71]])

In [112]:
#Change Dimesion of array
rand_arr = np.random.random((5,3))
rand_new = rand_arr[2:4]
rand_new

array([[0.89, 0.52, 0.34],
       [0.33, 0.86, 0.56]])

In [116]:
#Pretty print array by removing scientific notation
np.set_printoptions(suppress=False)
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.43e-04, 2.78e-04, 4.25e-04],
       [8.45e-04, 4.72e-06, 1.22e-04],
       [6.71e-04, 8.26e-04, 1.37e-04]])

In [120]:
np.set_printoptions(suppress=True, precision=6)
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

In [121]:
#Limit the output of array to fit
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [124]:
#Print array without truncating
np.set_printoptions(threshold=np.nan)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [131]:
#Import dataset with numners and text
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype ='object')
iris[1:3]

array([[b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [5]:
#extract a particular column from array
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=object)
species = np.array([row[4] for row in iris_1d])
species[:4]

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa'],
      dtype='|S15')

In [149]:
#Convert 1D array to 2D aray
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:4]

array([[b'5.1', b'3.5', b'1.4', b'0.2'],
       [b'4.9', b'3.0', b'1.4', b'0.2'],
       [b'4.7', b'3.2', b'1.3', b'0.2'],
       [b'4.6', b'3.1', b'1.5', b'0.2']], dtype='|S3')

In [150]:
#Comput mean, median and Standard Deviation of array
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
sepallength

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [151]:
mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mu, med, sd)

5.843333333333334 5.8 0.8253012917851409


In [152]:
#Find values excatly between 0 and 1
Smax, Smin = sepallength.max(), sepallength.min()
S = sepallength/Smax
print(S)

[0.64557  0.620253 0.594937 0.582278 0.632911 0.683544 0.582278 0.632911
 0.556962 0.620253 0.683544 0.607595 0.607595 0.544304 0.734177 0.721519
 0.683544 0.64557  0.721519 0.64557  0.683544 0.64557  0.582278 0.64557
 0.607595 0.632911 0.632911 0.658228 0.658228 0.594937 0.607595 0.683544
 0.658228 0.696203 0.620253 0.632911 0.696203 0.620253 0.556962 0.64557
 0.632911 0.56962  0.556962 0.632911 0.64557  0.607595 0.64557  0.582278
 0.670886 0.632911 0.886076 0.810127 0.873418 0.696203 0.822785 0.721519
 0.797468 0.620253 0.835443 0.658228 0.632911 0.746835 0.759494 0.772152
 0.708861 0.848101 0.708861 0.734177 0.78481  0.708861 0.746835 0.772152
 0.797468 0.772152 0.810127 0.835443 0.860759 0.848101 0.759494 0.721519
 0.696203 0.696203 0.734177 0.759494 0.683544 0.759494 0.848101 0.797468
 0.708861 0.696203 0.696203 0.772152 0.734177 0.632911 0.708861 0.721519
 0.721519 0.78481  0.64557  0.721519 0.797468 0.734177 0.898734 0.797468
 0.822785 0.962025 0.620253 0.924051 0.848101 0.91139

In [153]:
#https://stackoverflow.com/questions/34968722/how-to-implement-the-softmax-function-in-python
#Softmax function

In [159]:
#Find percentile score of array
np.percentile(sepallength, q=[5, 95])
#sepallength

array([4.6  , 7.255])

In [161]:
#Insert Value at random position in Array
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
print(iris_2d[:10])

[[b'5.1' b'3.5' b'1.4' b'nan']
 [b'4.9' b'3.0' b'1.4' b'0.2']
 [b'4.7' b'3.2' b'1.3' b'0.2']
 [b'4.6' b'3.1' b'1.5' b'0.2']
 [b'5.0' b'nan' b'1.4' b'0.2']
 [b'5.4' b'3.9' b'1.7' b'0.4']
 [b'4.6' b'3.4' b'1.4' b'0.3']
 [b'5.0' b'3.4' b'1.5' b'0.2']
 [b'4.4' b'2.9' b'1.4' b'0.2']
 [b'4.9' b'3.1' b'1.5' b'0.1']]


In [169]:
#Find correlation between two columns of array
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
np.corrcoef(iris[:,0],iris[:,2])[0,1]

0.871754157304871

In [172]:
#Find array has any null values
np.isnan(iris).any()

False

In [175]:
#Replace all Missing values with 0
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
iris_2d[np.isnan(iris_2d)] = 0
iris_2d[:4]

array([[5.1, 0. , 0. , 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [6]:
#Find the count of unique values in a array
iris = np.genfromtxt(url, delimiter=',', dtype='object')
S = np.array([row.tolist()[4] for row in iris])
np.unique(S)

array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
      dtype='|S15')

In [18]:
#Convert a numeric to a categorical[text] array
petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])
label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]
petal_length_cat[:4]

['small', 'small', 'small', 'small']

In [37]:
#Create new column from an existing column
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
sap_len = iris_2d[:, 0].astype('float')
pat_len = iris_2d[:, 2].astype('float')
vol = (np.pi * pat_len * (sap_len **2))/3
#Change axis of vol column
vol = vol[:, np.newaxis]
#Add the new column
out = np.hstack([iris_2d, vol])
out[:4]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa',
        38.13265162927291],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa',
        35.200498485922445],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa', 30.0723720777127],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa',
        33.238050274980004]], dtype=object)

In [59]:
#Get largest and second largest element when grouped by another element
#Create array of second column where species = Iris-setosa 
patel_len_satosa = iris[iris[:,4] == b'Iris-setosa',[2]]
#Get the Second largest last value
np.unique(np.sort(patel_len_satosa))[-2]
#Get the largest last value
np.unique(np.sort(patel_len_satosa))[-1]

b'1.9'

In [65]:
#Sort a 2D array by a column
print(iris[iris[:,0].argsort()])

[[b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'4.4' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'3.0' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.5' b'2.3' b'1.3' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.6' b'1.0' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.2' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.9' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.1' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.9' b'2.4' b'3.3' b'1.0' b'Iris-versicolor']
 [b'4.9' b'2.5' b'4.5' b'1.7' b'Iris-virginica']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.

In [76]:
#Find the most frequent value
val, counts = np.unique(iris[:,2], return_counts=True)
print(val[np.argmax(counts)])

b'1.5'


In [88]:
#Find the position of occurence of a value greater then given value
print(np.argmax(iris[:, 3].astype('float') > 2.0))
#Print array value like below 
#iris[np.argmax(iris[:, 3].astype('float') > 2.0)]

100


array([b'6.3', b'3.3', b'6.0', b'2.5', b'Iris-virginica'], dtype=object)

In [91]:
#Replace all values in Array with a given value
#Replace all values greater than 30 with 30 and less than 10 with 10
np.set_printoptions(precision=2)
a = np.random.uniform(1,50,20)
np.where(a<10,10,np.where(a>30,30,a))

array([10.  , 30.  , 30.  , 30.  , 25.03, 30.  , 30.  , 30.  , 10.  ,
       20.89, 21.44, 30.  , 21.82, 30.  , 30.  , 10.  , 15.79, 30.  ,
       10.  , 25.13])

In [97]:
#Get the postion of nth top values
np.sort(a)[-5:]

array([43.05, 45.22, 47.74, 48.11, 49.  ])

In [107]:
#Convert arrays into flat 1D array
arr1= np.arange(3)
arr2= np.arange(3,7)
array_of_arrays = np.array([arr1, arr2])
print('array_of_arrays: ', array_of_arrays)
new_array = np.concatenate(array_of_arrays)
new_array

array_of_arrays:  [array([0, 1, 2]) array([3, 4, 5, 6])]


array([0, 1, 2, 3, 4, 5, 6])

In [121]:
#Find maximum in each row
np.apply_along_axis(np.max, arr=iris, axis=0)

array([b'7.9', b'4.4', b'6.9', b'2.5', b'Iri'], dtype='|S3')

In [124]:
#Compute min and max for each row for a 2D array
#min divided by max
a = np.random.randint(1,10,[5,3])
print(a)
np.apply_along_axis(lambda x: np.min(x)/np.max(x),arr=a,axis=1)

[[6 5 1]
 [2 6 1]
 [2 1 5]
 [4 3 8]
 [7 4 8]]


array([0.17, 0.17, 0.2 , 0.38, 0.5 ])

In [131]:
#Find duplicate records in array
a = np.random.randint(0, 5, 10)
unique_positions = np.unique(a, return_index=True)[1]
print(a)
unique_positions

[0 4 0 1 1 3 4 3 0 0]


array([0, 3, 5, 1], dtype=int32)

In [134]:
#Find group mean
numeric_column = iris[:, 1].astype('float')  # sepalwidth
grouping_column = iris[:, 4]  # species
[[group_val, numeric_column[grouping_column==group_val].mean()] for group_val in np.unique(grouping_column)]


[[b'Iris-setosa', 3.418],
 [b'Iris-versicolor', 2.7700000000000005],
 [b'Iris-virginica', 2.974]]

In [138]:
#compute the euclidean distance between two arrays
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
dist = np.linalg.norm(a-b)
dist

6.708203932499369

In [140]:
#Subtract 1D array from 2D array
a = np.array([[3,3,3],[4,4,4],[5,5,5]])
b = np.array([1,1,3])
print(a - b[:,None])

[[2 2 2]
 [3 3 3]
 [2 2 2]]
